# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jumping Slug Community Cyclery
description: >- 
  The Jumping Slug Community Cyclery is a bike shop located in Port Alberni, Vancouver 
  Island. We specialize in all bike types: mountain, electric, gravel, adventure and road. 
  If you're looking for a new bike, expert servicing, rentals or a friendly chat, come check 
  us out!  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

phone: 250-724-6556
email: info@jumpingslug.com
address: 4961 Dundalk Ave S, Port Alberni, BC, V9Y 8P1
instagram_link: https://www.instagram.com/thejumpingslugcyclery/
facebook_link: https://www.facebook.com/thejumpingslug/

hours:
  hours_1: <b>10am to 5:30pm</b>, Tuesday through Friday
  hours_2: <b>9am to 4pm</b> on Saturday

notice:
  has_notice: false
  text: We will be closed <b>until July 30th</b> for a summer break. See you soon!

about_page:
  top_title: About Us
  top_blurb: >- 
    Located on the way into Port Alberni, The Jumping Slug offers top tier bike brands, 
    service and rentals for every type of bike. With a big focus on the biking community 
    in the Alberni valley, we host events and weekly group rides. For any information about 
    services, rentals or rides feel free to visit the shop, call or email us (we're friendly)!
  extra_blurbs:
    - blurb:
      title: Services
      text: >- 
        Our team provides expert maintenance services for all types of bikes. From flat tires 
        to tsunami tune maintenance packages, <u><a href="#services">learn more about our 
        pricing and services here</a></u>.
    - blurb:
      title: Rentals and Demos
      text: >- 
        Interested in checking out the trails or logging roads around Port Alberni or Vancouver 
        Island? We have mountain, electric, gravel and adventure bike rentals to suit your 
        needs. <u><a href="#rentals">Learn more about our pricing</a></u>!

service_packages:
  - level_1:
    primary_name: Level 1
    secondary_name: Safety Check Over
    price: $45
    timeframe: Recommended every 25+ hours
    note: E-bike add $25, parts extra
    items:
      - name: Align and Adjust brakes
      - name: Tune and adjust gears
      - name: Torque all fasteners
      - name: Inflate tires
  - level_2:
    primary_name: Level 2
    secondary_name: Basic Tune Up
    price: $75
    timeframe: Recommended every 50+ hours
    note: E-bike add $25, parts extra
    items:
      - name: Includes all level 1 services +
      - name: On the bike wheel true
      - name: Wash bike
      - name: Replace cable and housing
      - name: Test ride
  - level_3:
    primary_name: Level 3
    secondary_name: Advanced Tune Up
    price: $120
    timeframe: Recommended every 75+ hours
    note: E-bike add $50, parts extra
    items:
      - name: Includes all level 1 & 2 services +
      - name: Drivetrain clean in solvent tank
      - name: Off bike wheel true and tension
  - level_4:
    primary_name: Level 4
    secondary_name: Tsunami Tune
    price: $180
    timeframe: Recommended every 75+ hours
    note: E-bike add $50, parts extra
    items:
      - name: Includes all level 1, 2 & 3 services +
      - name: Service or replacement of BB & headset
      - name: Fork service 50HR (Add $60)
      - name: Rear shock 50HR (Add $40)

service_page:
  top_title: Service Packages
  top_text: >-
    We specialize in a wide variety of bikes, making them safe and actually enjoyable to 
    ride. <b>Just remember, all parts are extra!</b>
  middle_title: Individual Services
  middle_text: Our shop hourly rate is $70 per hour, or $100 per hour for e-bikes.

service_individuals:
  left_side:
    - item:
      price: $10
      name: Flat tire
    - item:
      price: $10
      name: Fix or replace chain
    - item:
      price: $30
      name: Flat tire (e-bike hub drive)
    - item:
      price: $20
      name: Set up tubeless (per wheel)
    - item:
      price: $30
      name: Brake bleed (per side)
    - item:
      price: $30
      name: Spoke replacement
    - item:
      price: $25
      name: Wheel true & tension
    - item:
      price: $80
      name: Wheel build
    - item:
      price: $40
      name: Box bike
    - item:
      price: $75
      name: Assemble bike
  right_side:
    - item:
      price: $10
      name: Gear adjust (per side)
    - item:
      price: $10
      name: Brake adjust (per side)
    - item:
      price: $70
      name: Fork service 50HR
    - item:
      price: $125
      name: Fork service 150HR
    - item:
      price: $50
      name: Rear shock service 50HR
    - item:
      price: $125
      name: Rear shock service 150HR
    - item:
      price: $40
      name: Dropper post service
    - item:
      price: $30
      name: Replace BB
    - item:
      price: $50
      name: Replace headset
    - item:
      price: $10
      name: Replace sealed bearing
  
rental_page:
  top_title: Rentals and Demos
  top_text: >- 
    Take one of our bikes for a spin or an overnight adventure! All rental and demo fees 
    go towards a purchase of a new bike (within 30 days). Helmets, knee pads and bags are 
    also available for rent.

rentals:
  - item:
    primary_name: MTB
    secondary_name: Rental
    prices:
      - item:
        price: $70
        name: 4 hours
      - item:
        price: $100
        name: 8 hours
      - item:
        price: $110
        name: 1 day
      - item:
        price: $400
        name: 7 days
  - item:
    primary_name: E-Bike
    secondary_name: Rental
    prices:
      - item:
        price: $90
        name: 4 hours
      - item:
        price: $120
        name: 8 hours
      - item:
        price: $130
        name: 1 day
      - item:
        price: $500
        name: 7 days
  - item:
    primary_name: Adv./Gravel
    secondary_name: Rental
    prices:
      - item:
        price: $70
        name: 4 hours
      - item:
        price: $100
        name: 8 hours
      - item:
        price: $110
        name: 1 day
      - item:
        price: $400
        name: 7 days
  - item:
    primary_name: Demo
    secondary_name: Program
    prices:
      - item:
        price: $70
        name: 4 hours
      - item:
        price: $100
        name: 8 hours
      - item:
        price: $110
        name: 1 day
      - item:
        price: $400
        name: 7 days

team_page:
  top_title: Our Team
  top_text: The people that make us so great!

team_members_top:
  - member:
    name: Lee Blais
    photo: images/team/lee.jpg
    title: Owner
    text: >- 
      Lee spends a lot of time traveling around the island backroads by bike. If you want 
      to check out cool remote locations, talk to this guy.
  - member:
    name: Nik Kay
    photo: images/team/nik.jpg
    title: Senior Mechanic
    text: Specializing in Tsunami tune ups and going fast, Nik is our resident pro racer.
  - member: 
    name: Jeremy Robson
    photo: images/team/jeremy.jpg
    title: Mechanic
    text: Hey! I need a blurb! Let me know what to say!

team_members_bottom:
  - member:
    name: Kyle Sketsch
    photo: images/team/kyle.jpg
    title: Sales
    text: Hey! I need a blurb! Let me know what to say!
  - member:
    name: Cortland Thibodeau
    photo: images/team/cortland.jpg
    title: Tech Guy
    text: Self proclaimed shop internet nerd. Cortland does the photography and website.

brand_page:
  top_title: We feature top-tier brands!
  top_text: Here are a few of our favourites.

brands:
  - item:
    img: images/brands/surly_logo.png
    link: https://surlybikes.com
    alt: Surly Bikes
  - item:
    img: images/brands/devinci_logo.png
    link: https://www.devinci.com/
    alt: Devinci Bikes
  - item:
    img: images/brands/trek_logo.png
    link: https://www.trekbikes.com/ca/en_CA/
    alt: Trek Bikes
  - item:
    img: images/brands/knolly_logo.png
    link: https://knollybikes.com/
    alt: Knolly Bikes
  - item:
    img: images/brands/cannondale_logo.png
    link: https://www.cannondale.com/
    alt: Cannondale Bikes
  - item:
    img: images/brands/marin_logo.png
    link: https://www.marinbikes.com/
    alt: Marin Bikes
  - item:
    img: images/brands/oneup_logo.png
    link: https://can.oneupcomponents.com
    alt: OneUp Components
  - item:
    img: images/brands/raceface_logo.png
    link: https://www.raceface.com/
    alt: Raceface Components
  - item:
    img: images/brands/chromag_logo.png
    link: https://chromagbikes.com/
    alt: Chromag Bikes
  - item:
    img: images/brands/rockshox_logo.png
    link: https://www.sram.com/en/rockshox
    alt: Rockshox Suspension
  - item:
    img: images/brands/100_percent_logo.png
    link: https://www.100percent.com/
    alt: 100 Percent
  - item:
    img: images/brands/revelatedesigns_logo.png
    link: http://www.revelatedesigns.com/
    alt: Revelate Designs
  - item:
    img: images/brands/gorebike_logo.png
    link: https://www.gorewear.com/
    alt: Gore Bike Wear



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
